version: "3.9"

services:
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    deploy:
         resources:
            limits:
               cpus: "3"
               memory: "1024M"

  django:
    build:
      context: .
    container_name: django
    env_file: .env
    volumes:
      - ./app:/app
      - static_volume:/app/staticfiles
      - ./logs:/app/proyecto/logs
    depends_on:
      - db
    expose:
      - "8000"
    user: "1000:1000"
    deploy:
         resources:
            limits:
               cpus: "3"
               memory: "1024M"

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - static_volume:/static
    depends_on:
      - django
    deploy:
         resources:
            limits:
               cpus: "3"
               memory: "1024M"

volumes:
  db_data:
  static_volume:
